---
title: "UV Index Plots"
author: "HackSmith 2021"
date: "3/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE)
```

```{r}
library(tidyverse)
library(lubridate)
library(rjson)
library(jsonlite)
library(RCurl)
```

## Get data
```{r}
# get uv index hourly given zip code
uv_userzip <- function(zip_arg){
  zipbase_url <- "https://enviro.epa.gov/enviro/efservice/getEnvirofactsUVHOURLY/ZIP/"
  zipfull_url <- paste0(zipbase_url, zip_arg, "/JSON")
  uvdatazip <- fromJSON(readLines(zipfull_url))
  return(uvdatazip)
}

uvdatazip = uv_userzip("85323")
```

```{r}
# get uv index hourly given city, state
uv_usercity <- function(city_arg, state_arg){
  citybase_url <- "https://enviro.epa.gov/enviro/efservice/getEnvirofactsUVHOURLY/CITY/"
  cityfull_url <- paste0(citybase_url, city_arg, "/STATE/", state_arg, "/JSON")
  uvdatacity <- fromJSON(readLines(cityfull_url))
  return(uvdatacity)
}

uvdatacity = uv_usercity("san jose", "ca")
```

```{r}
# convert time
uv_converttime <- function(uvdf){
  uvdf <- uvdf %>%
    mutate(NEW_DATE = mdy_h(DATE_TIME))
  return(uvdf)
}
uvdatacity = uv_converttime(uvdatacity)
uvdatazip = uv_converttime(uvdatazip)
```

## UV Index Classifications
```{r}
uvrisk <- data.frame(name = c("Low", "Moderate", "High", "Very High"),
                    imin = c(0,3,6,8),
                    imax = c(3,6,8,11),
                    mycolor = c("A", "B", "C", "D")) %>%
  mutate(medy = imin + floor((imax-imin)/2))
```


## Plots
```{r}
uv_plot <- function(uvdf){
  ggplot() +
    theme_light() +
  geom_rect(data = uvrisk, aes(xmin = c(uvdf$NEW_DATE[1], uvdf$NEW_DATE[1], uvdf$NEW_DATE[1], uvdf$NEW_DATE[1]), xmax = c(uvdf$NEW_DATE[21], uvdf$NEW_DATE[21], uvdf$NEW_DATE[21], uvdf$NEW_DATE[21]), ymin = imin, ymax = imax, fill = mycolor)) +
  geom_text(data = uvrisk, aes(x = uvdf$NEW_DATE[3], y = medy, label = name, size = 3))+
  geom_line(data = uvdf, aes(x = NEW_DATE, y = UV_VALUE)) +
  scale_y_continuous("UV Index", limit = c(-0.1, 11), breaks = c(0,1,2,3,4,5,6,7,8,9,10,11), expand = c(0, 0)) +
  #scale_x_continuous(expand = c(0,0)) +
  ggtitle("UV Index in the Past Day") +
  theme(axis.title.x = element_blank(),
        legend.position = "None") 
    
}

uv_plot(uvdatacity)
uv_plot(uvdatazip)
  
```

